name: CI

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".*"
  push:
    branches:
      - main
      - 'release-*'

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spark-connector-oceanbase:
    uses: ./.github/workflows/test.yml
    with:
      module: spark-connector-oceanbase/spark-connector-oceanbase-base

  spark-connector-obkv-hbase:
    uses: ./.github/workflows/test.yml
    with:
      module: spark-connector-obkv-hbase/spark-connector-obkv-hbase-base

  e2e-tests:
    strategy:
      matrix:
        spark_version: ["v3.1.3","3.2.4","3.3.3","3.4.4","3.5.5"]
    uses: ./.github/workflows/test.yml
    with:
      module: spark-connector-oceanbase-e2e-tests
      maven_opts: "-D spark_version=${{ matrix.spark_version }}"

  e2e-tests-scala-2_11:
    strategy:
      matrix:
        spark_version: ["2.4.6"]
    uses: ./.github/workflows/test.yml
    with:
      module: spark-connector-oceanbase-e2e-tests
      maven_opts: "-D skipTests -D spark_version=${{ matrix.spark_version }} -D scala.version=2.11.12 -D scala.binary.version=2.11"

  e2e-tests-scala-2_13:
    strategy:
      matrix:
        spark_version: [ "3.5.5" ]
    uses: ./.github/workflows/test.yml
    with:
      module: spark-connector-oceanbase-e2e-tests
      maven_opts: "-D skipTests -D spark_version=${{ matrix.spark_version }} -D scala.version=2.13.15 -D scala.binary.version=2.13"

